### PR TITLE
Feature/net standard

### PR DESCRIPTION
**Pull request by ryandanthony**
Moved jsreport.Client to .net standard. 

Unit tests run successfully. 
I created a pack.ps1 and push.ps1. 
I had to split out jsreport.Client.HttpHandler due to its dependency on System.Web (not available in netstandard)
The other projects are all built for  .net 4.6

### CODE REVIEW

**Comment by pofider** [comment]
Thank you, I'll look into it ASAP.

**Comment by pofider** [comment]
I apologize for the delay. I had to find the time to understand better new .net terminology. Your PR was perfect in this and saved me a lot of time.

I'll postpone a bit release to nuget, because I want to include some additional improvements in the release 2. However this should not take long.

Thank you again!

**Comment by pofider** [comment]
The summary of planned changes can be found here https://github.com/jsreport/net/issues/24

**Comment by ryandanthony** [comment]
Is it possible to get a build of the jsreport.client nuget package out onto nuget.org? We are at the point where we need to take a dependency on it for a .net core project.

**Comment by pofider** [comment]
I'm still not finish with my changes, but I'm working on it and getting closer. It should be in the next days in git repositories.

The think is that I don't want to put to nuget your original version because it is breaking and I would need to release it with version 2 and right after release version 3 with my new stuff.  Could you just link the dll into your project for now?

**Comment by sdmackay** [comment]
Any news on when your going to get V2 out to nuget? I would love to use it in my asp.net core project.

**Comment by pofider** [comment]
The v2 is now in the nugget as "prerelease". Some further information can be found here.

https://github.com/jsreport/jsreport-dotnet
https://jsreport.net/learn/dotnet-v2

**Pull request merged**
